config/routes.rb
StoryRough::Application.routes.draw do

    resources :authors do
    	member do
    		get :following, :followers, :projects
    	end
    end
    resources :projects do
    	resources :chapters, :characters, :locations, :pictures
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :author_statuses, only: [:create, :destroy]
    resources :author_authors, only: [:create, :destroy]

  get "authors/new"
  match '/signup', to: 'authors#new'

	root to: 'static_pages#home'
	
	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
    
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :email, :location, :summary, :username, :password, :password_confirmation
  has_many :author_statuses, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :author_authors, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_authors, through: :author_authors, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
  									class_name: "AuthorAuthor",
  									dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  has_secure_password
  
  before_create :default_values
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  before_save :default_values
  
  validates :username, presence: true, length: { maximum:50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true
  
  def feed
	AuthorStatus.from_users_followed_by(self)
  end
  
  def following?(other_author)
  	author_authors.find_by_followed_id(other_author.id)
  end
  
  def follow!(other_author)
  	author_authors.create!(followed_id: other_author.id)
  end
  
  def unfollow!(other_author)
  	author_authors.find_by_followed_id(other_author.id).destroy
  end
  
  private
    def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
    end
  
  	def default_values
  		self.location ||= ''
  		self.summary ||= ''
  	end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_filter :signed_in_author, only: [:edit, :update, :destroy, :following, :followers]
    before_filter :correct_author, only: [:edit, :update]
    before_filter :admin_author, only: :destroy
    
    def show
        @author = Author.find(params[:id])
        @author_statuses = @author.author_statuses.paginate(page: params[:page])
    end
    
    def new
        @author = Author.new
    end
    
    def create
        @author = Author.new(params[:author])
        if @author.save
            sign_in @author
            flash[:success] = "Welcome to the club!"
            redirect_to @author
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @author.update_attributes(params[:author])
            flash[:success] = "Profile updated"
            sign_in @author
            redirect_to @author
        else
            render 'edit'
        end
    end
    
    def index
        @authors = Author.paginate(page: params[:page])
    end
    
    def destroy
    	Author.find(params[:id]).destroy
    	flash[:success] = "Author destroyed"
    	redirect_to authors_url
    end
    
    def following
    	@title = "Following"
    	@author = Author.find(params[:id])
    	@authors = @author.followed_authors.paginate(page: params[:page])
    	render 'show_follow'
    end
    
    def followers
    	@title = "Followers"
    	@author = Author.find(params[:id])
    	@authors = @author.followers.paginate(page: params[:page])
    	render 'show_follow'
    end
    
    def projects
    	@author = Author.find(params[:id])
    	@projects = @author.projects.paginate(page: params[:page])
    	render 'show_projects'
    end
    	   
    private
        
        def correct_author
            @author = Author.find(params[:id])
            redirect_to(root_path) unless current_author?(@author)
        end
        
        def admin_author
        	redirect_to(root_path) unless current_author.admin?
        end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<li>

<p><span class='name'><%= link_to author.username, author %></span> | <%= author.location %> | <%= pluralize(author.projects.length, 'project') %></p>
<p><%= if author.summary.length > 0 then author.summary else "I am a creative soul!" end %></p>

<% if current_author && current_author.admin? && !current_author?(author) %>
	<div class="delete"><%= link_to "delete", author, method: :delete, data: {confirm: "Are you sure you want to delete " + author.username + "?"} %></div>
<% end %>

</li>

app/views/authors/_follow.html.erb
<%= form_for(current_author.author_authors.build(followed_id: @author.id), remote: true) do |f| %>
<%= f.hidden_field :followed_id %>
<%= f.submit "Follow" %>
<% end %>

app/views/authors/_follow_form.html.erb
<% unless current_author?(@author) %>
	<% if current_author.following?(@author) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
<% end %>

app/views/authors/_unfollow.html.erb
<%= form_for(current_author.author_authors.find_by_followed_id(@author), html: {method: :delete }, remote: true) do |f| %>
<%= f.submit "Unfollow" %>
<% end %>

app/views/authors/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<%= form_for(@author) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :username %>
<%= f.text_field :username %><br>

<%= f.label :location %>
<%= f.text_field :location %><br>

<%= f.label :summary %>
<%= f.text_area :summary %><br>

<%= f.label :password %>
<%= f.password_field :password %><br>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %><br>

<%= f.submit "Save changes" %>
<% end %>

app/views/authors/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<div class="pag"><%= will_paginate %></div>

<ul class="indexList">
<%= render @authors %>
</ul>

<div class="pag"><%= will_paginate %></div>

app/views/authors/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<%= form_for(@author) do |f| %>
<%= render 'shared/error_messages', object: f.object %><br>

<%= f.label :username %>
<%= f.text_field :username %><br>

<%= f.label :email %>
<%= f.text_field :email %><br>

<%= f.label :password %>
<%= f.password_field :password %><br>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %><br>

<%= f.submit "Create my account" %>
<% end %>

app/views/authors/show.html.erb
<% @author ||= current_author %>
<% provide(:title, @author.username) %>
<h1><%= @author.username %></h1>
<p><b><%= @author.location %></b> <%= link_to "Projects", projects_author_path(@author.id) %></p>

<div class="authorNav">
<ul>
<li><%= link_to "Projects", projects_author_path(@author.id) %></li>
<li><a href="<%= followers_author_path(@author) %>">watched by <%= pluralize(@author.followers.count, 'author') %></a></li>
<li><%= link_to "Favorites", '#' %></li>
</ul>
</div>

<%= render 'follow_form' if signed_in? %>


<p><%= @author.summary %></p>

<div class="statusIndex">
<% if @author.author_statuses.any? %>
<h3>Statuses: <%= @author.author_statuses.count %></h3>
<ul>
<%= render @author_statuses %>
</ul>
<div class="pag"><%= will_paginate @author_statuses %>
<% end %>
</div>

app/views/authors/show_follow.html.erb
<% provide(:title, @title) %>
<h1><%= @author.username %></h1>
<p><%= link_to "View my Profile", @author %></p>
<b>Statuses:</b> <%= @author.author_statuses.count %>

<%= render 'shared/stats' %>

<h3><%= @title %></h3>
<% if @authors.any? %>
<%= render @authors %>
<div class="pag"><%= will_paginate %></div>
<% end %>

app/views/authors/show_projects.html.erb
<% provide(:title, "Projects") %>

<h1>Projects</h1>

<p>by <%= link_to @author.username, @author %></p>

<% if current_author?(@author) %>
	<p><div class="newProj"><%= link_to "New Project", new_project_path %></div></p>
<% end %>

<ul class="indexList">
<% if @projects.any? %>
<%= render @projects %>
<% end %>
</ul>

<div class="pag"><%= will_paginate @projects %></div>