config/routes.rb
StoryRough::Application.routes.draw do

    resources :authors do
    	member do
    		get :following, :followers, :projects
    	end
    end
    resources :projects do
    	resources :chapters, :characters, :locations, :pictures
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :author_statuses, only: [:create, :destroy]
    resources :author_authors, only: [:create, :destroy]

  get "authors/new"
  match '/signup', to: 'authors#new'

	root to: 'static_pages#home'
	
	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
    
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :elevator, :name, :notes, :skeleton
  belongs_to :author
  has_many :outlines, dependent: :destroy
  has_many :chapters, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :pictures, dependent: :destroy
  
  before_create :create_notice
	before_save :add_update
  
    default_scope order: 'projects.updated_at DESC'
  
  validates :name, presence: true
  validates :author_id, presence: true
  
  private
  	def add_update
  		author = Author.find(author_id)
  		string = '<%= link_to @self.name, @self %>'
  		author.author_statuses.create!(status: "%s updated %{title}" %{name: author.username, title: string}) 
  	end
  	
  	def create_notice
  		author = Author.find(author_id)
  		string = '<%= link_to @self.name, @self %>'
  		author.author_statuses.create!(status: "%{name} has created a new project! %{title}" %{name: author.username, title: string})
  	end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :signed_in_author, only: [:edit, :update, :destroy]
    before_filter :correct_author, only: [:edit, :update, :destroy]

    def show
        @project = Project.find(params[:id])
        @chapters = @project.chapters
    end
    
    def new
        @project = Project.new
    end

	def create
	  @project = current_author.projects.build(params[:project])
	  if @project.save
	  	flash[:success] = "Project created"
		redirect_to @project
	  else
		render 'new'
	  end
	end
	
	def edit
	end
	
	def update
	  if @project.update_attributes(params[:project])
		flash[:success] = "Project updated"
		redirect_to @project
	  else
		render 'edit'
	  end
	end
	
	def index(id=nil)
		@projects = Project.paginate(page: params[:page])
		@index = true
	end
	
	def destroy
		@project.destroy
    	flash[:success] = "Project destroyed"
    	redirect_to projects_url
	end

  private
	def correct_author
	  	@project = current_author.projects.find_by_id(params[:id])
		@trueProject = Project.find_by_id(params[:id])
		redirect_to @trueProject if @project.nil?
	end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li>


<p><span class="name"><%= link_to project.name, project %></span> by <span class="author"><%= link_to project.author.username, project.author %></span></p>
<p><span class="projTime">updated <%= time_ago_in_words(project.updated_at) %> ago</span></p>
<p><%= project.elevator %></p>
<% if not @index %>
	<div class="delete"><%= link_to "delete", project, method: :delete, data: {confirm: "Are you sure you want to delete " + project.name + "?"} %></div>
<% end %>

</li>

app/views/projects/edit.html.erb
<% provide(:title, "Edit " + @project.name) %>

<h1>Edit <%= @project.name %></h1>

<%= form_for(@project) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :elevator %>
<%= f.text_field :elevator %><br>

<%= f.label :skeleton %>
<%= f.text_area :skeleton %><br>

<%= f.label :notes %>
<%= f.text_area :notes %><br>

<%= f.submit "Update Project" %>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, "All projects") %>
<h1>All projects</h1>

<div class="pag"><%= will_paginate %></div>

<ul class="indexList">
<%= render @projects %>
</ul>

<div class="pag"><%= will_paginate %></div>

app/views/projects/new.html.erb
<% provide(:title, "New Project") %>

<h1>New Project</h1>

<%= form_for(@project) do |f| %>
<%= render 'shared/error_messages', object: f.object %><br>

<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :elevator %>
<%= f.text_field :elevator %><br>

<%= f.submit "Create new project" %>
<% end %>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>

<% if signed_in? && current_author?(@project.author) %>
<%= link_to "<<< Back to projects", projects_author_path(current_author.id) %>
<% end %>

<h1><%= @project.name %></h1>
<p>by <%= link_to @project.author.username, @project.author %></p>
<% if signed_in? && current_author?(@project.author) %>
<p><i><%= link_to "Edit", edit_project_path %></i></p>
<% end %>
<p><i><%= @project.elevator %></i></p>

<p><%= @project.skeleton %></p>

<pre>
<%= @project.notes %></p>
</pre>

<p><%= link_to "Chapters", project_chapters_path(@project.id) %></p>