config/routes.rb
StoryRough::Application.routes.draw do

    resources :authors do
    	member do
    		get :following, :followers, :projects
    	end
    end
    resources :projects do
    	resources :chapters, :characters, :locations, :pictures
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :author_statuses, only: [:create, :destroy]
    resources :author_authors, only: [:create, :destroy]

  get "authors/new"
  match '/signup', to: 'authors#new'

	root to: 'static_pages#home'
	
	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
    
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :body, :notes, :project_id, :title
  belongs_to :project

  
  validates :project_id, presence: true
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
    before_filter :signed_in_author, only: [:edit, :update, :destroy]
    before_filter :correct_author, only: [:create, :edit, :update, :destroy]

  def new
  	@project = Project.find_by_id(params[:project_id])
  	@chapter = @project.chapters.new
  end

  def show
  	@project = Project.find_by_id(params[:project_id])
  	@chapter = Chapter.find(params[:id])
  end

  def index
  	@project = Project.find(params[:project_id])
  	@chapters = Chapter.paginate(page: params[:page])
  end

# get project id in hidden field in creation form
  def create
	@project = Project.find(params[:project_id])
	@chapter = @project.chapters.build(params[:chapter])
	if @chapter.save
	  	flash[:success] = "Chapter created"
		redirect_to project_chapter_path(@project, @chapter)
	  else
		render 'new'
	end
  end
  
  def edit
  	@project = Project.find(params[:project_id])
  	@chapter = Chapter.find(params[:id])
  end

  def update
  	@project = Project.find(params[:project_id])
  	@chapter = Chapter.find(params[:id])
  	if @chapter.update_attributes(params[:chapter])
		flash[:success] = "Chapter updated"
		redirect_to project_chapter_path(@project, @chapter)
	else
		render 'edit'
	end
  end

  def destroy
  	@project = Project.find(params[:project_id])
  	@chapter = Chapter.find(params[:id])
  	@chapter.destroy
    flash[:success] = "Chapter destroyed"
    redirect_to @project
  end
  
  private
	def correct_author
	  @project = Project.find_by_id(params[:project_id])
	  @trueAuthor = @project.author
	  redirect_to current_author if @trueAuthor != current_author
	end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_chapter.html.erb
<li>
<%= link_to chapter.title, project_chapter_path(chapter.project, chapter) %>
</li>

<% if current_author?(chapter.project.author) %>
	<div class="delete"><%= link_to "delete", [chapter.project, chapter], method: :delete, data: {confirm: "Are you sure you want to delete " + chapter.title + "?"} %></div>
<% end %>

app/views/chapters/edit.html.erb
<% provide(:title, "Edit " + @project.name) %>

<h1>Edit <%= @chapter.title %></h1>

<%= form_for([@project, @chapter]) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :title %>
<%= f.text_field :title %><br>

<%= f.label :body %>
<%= f.text_field :body %><br>

<%= f.label :notes %>
<%= f.text_area :notes %><br>

<%= f.submit "Update Chapter" %>
<% end %>

app/views/chapters/index.html.erb
<h1>Chapters for <%= @project.name %></h1>

<p>by <%= link_to @project.author.username, @project.author %></p>
<% if signed_in? && current_author?(@project.author) %>
<p><i><%= link_to "New Chapter", new_project_chapter_path(@project) %></i></p>
<% end %>

<ul class="indexList">
<% if @chapters.any? %>
<%= render @chapters %>
<% end %>
</ul>

<div class="pag"><%= will_paginate @chapter %></div>

app/views/chapters/new.html.erb
<% provide(:title, "New Chapter") %>

<h1>New Chapter</h1>

<%= form_for([@project, @chapter]) do |f| %>
<%= render 'shared/error_messages', object: f.object %><br>

<%= f.label :title %>
<%= f.text_field :title %><br>

<%= f.label :body %>
<%= f.text_field :body %><br>

<%= f.label :notes %>
<%= f.text_field :notes %>

<%= f.submit "Create new project" %>
<% end %>

app/views/chapters/show.html.erb
<p><%= link_to "Back to Chapter List", project_chapters_path(@project) %></p>
<h1><%= @chapter.title %></h1>

<% if signed_in? && current_author?(@project.author) %>
<p><i><%= link_to "Edit", edit_project_chapter_path(@project) %></i></p>
<% end %>

<p><%= @chapter.body %></p>
<p><%= @chapter.notes %></p>