config/routes.rb
StoryRough::Application.routes.draw do

    resources :authors do
    	member do
    		get :following, :followers, :projects
    	end
    end
    resources :projects do
    	resources :chapters, :characters, :locations, :pictures
    end
    resources :sessions, only: [:new, :create, :destroy]
    resources :author_statuses, only: [:create, :destroy]
    resources :author_authors, only: [:create, :destroy]

  get "authors/new"
  match '/signup', to: 'authors#new'

	root to: 'static_pages#home'
	
	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
    
    match '/signin', to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :email, :location, :summary, :username, :password, :password_confirmation
  has_many :author_statuses, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :author_authors, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_authors, through: :author_authors, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id",
  									class_name: "AuthorAuthor",
  									dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  has_secure_password
  
  before_create :default_values
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  before_save :default_values
  
  validates :username, presence: true, length: { maximum:50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6}
  validates :password_confirmation, presence: true
  
  def feed
	AuthorStatus.from_users_followed_by(self)
  end
  
  def following?(other_author)
  	author_authors.find_by_followed_id(other_author.id)
  end
  
  def follow!(other_author)
  	author_authors.create!(followed_id: other_author.id)
  end
  
  def unfollow!(other_author)
  	author_authors.find_by_followed_id(other_author.id).destroy
  end
  
  private
    def create_remember_token
        self.remember_token = SecureRandom.urlsafe_base64
    end
  
  	def default_values
  		self.location ||= ''
  		self.summary ||= ''
  	end
  
end

app/models/author_author.rb
class AuthorAuthor < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  
  belongs_to :follower, class_name: "Author"
  belongs_to :followed, class_name: "Author"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/author_status.rb
class AuthorStatus < ActiveRecord::Base
  attr_accessible :status
  belongs_to :author
  
  validates :author_id, presence: true
  validates :status, presence: true, length: { maximum: 250 }
  
  default_scope order: 'author_statuses.created_at DESC'
  
  def self.from_users_followed_by(author)
  	followed_author_ids = "SELECT followed_id FROM author_authors WHERE follower_id = :author_id"
  	where("author_id IN (#{followed_author_ids}) OR author_id = :author_id", followed_author_ids: followed_author_ids, author_id: author)
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :body, :notes, :project_id, :title
  belongs_to :project

  
  validates :project_id, presence: true
end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :elevator, :name, :project_id
  belongs_to :project
  has_many :character_summaries, dependent: :destroy
  
  validates :name, presence: true
  validates :project_id, presence: true
end

app/models/character_summary.rb
class CharacterSummary < ActiveRecord::Base
  attr_accessible :body, :character_id, :heading
  belongs_to :character
  
  validates :character_id, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :elevator, :name, :project_id
  belongs_to :project
  has_many :location_summaries, dependent: :destroy
  
  validates :project_id, presence: true
  validates :name, presence: true
end

app/models/location_summary.rb
class LocationSummary < ActiveRecord::Base
  attr_accessible :body, :heading, :location_id
  belongs_to :location
  
  validates :location_id, presence: true
end

app/models/outline.rb
class Outline < ActiveRecord::Base
  attr_accessible :description, :notes, :order, :project_id, :title
  belongs_to :project
  
  validates :project_id, presence: true
  validates :order, presence: true
  validates :title, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :location, :name, :project_id
  belongs_to :project
  
  validates :project_id, presence: true
  validates :location, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :elevator, :name, :notes, :skeleton
  belongs_to :author
  has_many :outlines, dependent: :destroy
  has_many :chapters, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :pictures, dependent: :destroy
  
  before_create :create_notice
	before_save :add_update
  
    default_scope order: 'projects.updated_at DESC'
  
  validates :name, presence: true
  validates :author_id, presence: true
  
  private
  	def add_update
  		author = Author.find(author_id)
  		string = '<%= link_to @self.name, @self %>'
  		author.author_statuses.create!(status: "%s updated %{title}" %{name: author.username, title: string}) 
  	end
  	
  	def create_notice
  		author = Author.find(author_id)
  		string = '<%= link_to @self.name, @self %>'
  		author.author_statuses.create!(status: "%{name} has created a new project! %{title}" %{name: author.username, title: string})
  	end
  
end

app/models/project_status.rb
class ProjectStatus < ActiveRecord::Base
  attr_accessible :project_id, :status
  belongs_to :project
end

app/models/project_update.rb
class ProjectUpdate < ActiveRecord::Base
  attr_accessible :project_id, :update
  belongs_to :project
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_authors_helper.rb
module AuthorAuthorsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(author)
        cookies.permanent[:remember_token] = author.remember_token
        self.current_author = author
    end
    
    def sign_out
        self.current_author = nil
        cookies.delete(:remember_token)
    end
    
    def signed_in?
        !current_author.nil?
    end
    
    def current_author=(author)
        @current_author = author
    end
    
    def current_author
        @current_author ||= Author.find_by_remember_token(cookies[:remember_token])
    end
    
    def current_author?(author)
        author == current_author
    end
    
    def redirect_back_or(default)
        redirect_to(session[:return_to] || default)
        session.delete(:return_to)
    end
    
    def store_location
        session[:return_to] = request.url
    end
    
    def current_author?(author)
    	author == current_author
    end
    
    def signed_in_author
    	unless signed_in?
    		store_location
    		redirect_to signin_url, notice: "Please sign in"
    	end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">

<div class="footNav">
<ul>
<li><%= link_to "Home", root_path %></li>
<li> | </li>
<li><%= link_to "About", about_path %></li>
<li> | </li>
<li><%= link_to "Contact", contact_path %></li>
<li> | </li>
<li><%= link_to "Help", help_path %></li>
</ul>
</div>


</div>

app/views/layouts/_header.html.erb
<div class="header">
<div class="projHead"><%= link_to "Story Manager", root_path%></div>

<div class="navHead">
<ul>
<% if signed_in? %>
<li><%= link_to current_author.username, current_author %></li>
<li> | </li>
<% end %>

<li><%= link_to "Authors", authors_path %></li>
<li><%= link_to "All Projects", projects_path %></li>
<% if signed_in? %>
<li> | </li>
<%= link_to "Projects", projects_author_path(current_author.id) %>
<li><%= link_to "Settings", edit_author_path(current_author) %></li>
<li> | </li>
<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
<% else %>

<li><%= link_to "Sign In", signin_path %></li>
<% end %> 

</ul>
</div><!-- end nav -->

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Story Organizer Dev | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="content">

<ul>
<% flash.each do |key, value| %>
<li><%= value %></li>
<% end %>
</ul>

<%= yield %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>

</div>

</body>
</html>

app/views/shared/_author_info.html.erb
<h1><%= current_author.username %></h1>
<%= link_to "view my profile", current_author %>
<%= pluralize(current_author.author_statuses.count, "status") %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<p>The form contains <%= pluralize(object.errors.count, "error") %>.</p>
<ul><% object.errors.full_messages.each do |msg| %>
<li>* <%= msg %></li>
<% end %>
</ul>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol>
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<div class="pag"><%= will_paginate @feed_items %></div>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
<%= link_to feed_item.author.username, feed_item.author %>

<span class="content"><%= feed_item.status %></span>
<span class="timestamp">Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</span>
<% if current_author?(feed_item.author) %>
<%= link_to "delete", feed_item, method: :delete, data: {confirm:"You sure?"}, title: feed_item.status %>.
<% end %>
</li>

app/views/shared/_stats.html.erb
<% @author ||= current_author %>
<a href="<%= following_author_path(@author) %>"><%= @author.followed_authors.count %> following</a>
<a href="<%= followers_author_path(@author) %>"><%= @author.followers.count %> followers</a>

app/views/shared/_status_form.html.erb
<%= form_for(@author_status) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<%= f.text_area :status, placeholder: "New status:" %>
<%= f.submit "Post" %>
<% end %>